import Provider from '@/providers';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '700'],
});

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className} ${poppins.className} antialiased`}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
